### ISSUE TITLE
Las imágenes se guardan en el servicio y los dockerfiles no lo encuentran.

### ISSUE THREAD

**Issue by rsanchezavalos** [nanounanue/pipeline-template#4]
El bash script "registrar.sh" guarda las imágenes en el servicio localhost:5000/***  y los dockerfiles llaman desde  /dpa/python:0.1 y no los encuentra. 

No estoy seguro si inicié bien el servicio hay que adaptar el dockerfile a localhost:5000/dpa/python:0.1
R.

**Comment by nanounanue** [comment]
Mmm no entendí, ¿a qué te refieres?

**Comment by rsanchezavalos** [comment]
Ya entedí 
el código que buildea las imágenes asigna el tag con el ${DOCKER_REGISTRY}/ al inicio para hacerle push al servicio y todos los nodos puedan ver las imágenes, pero los dockerfiles de las imágenes de prueba la buscan solo con el tag /dpa/${IMAGE}:${IMAGE_VERSION}. Solo tuve que agregar el tag sin el docker_registry para que el nodo 1 pudiera construirlas. 

`for IMAGE in ${IMAGES} ; do
    docker build --tag ${DOCKER_REGISTRY}/dpa/${IMAGE}:${IMAGE_VERSION} tasks/${IMAGE}
    docker push ${DOCKER_REGISTRY}/dpa/${IMAGE}:${IMAGE_VERSION}
done
`
